// Code generated by goctl. DO NOT EDIT!
// Source: agent.proto

package server

import (
	"context"

	"github.com/hongyuxuan/lizardrestic/agent/internal/logic"
	"github.com/hongyuxuan/lizardrestic/agent/internal/svc"
	"github.com/hongyuxuan/lizardrestic/agent/types/agent"
)

type LizardAgentServer struct {
	svcCtx *svc.ServiceContext
	agent.UnimplementedLizardAgentServer
}

func NewLizardAgentServer(svcCtx *svc.ServiceContext) *LizardAgentServer {
	return &LizardAgentServer{
		svcCtx: svcCtx,
	}
}

func (s *LizardAgentServer) SetEnvironment(ctx context.Context, in *agent.SetEnvironmentRequest) (*agent.Response, error) {
	l := logic.NewSetEnvironmentLogic(ctx, s.svcCtx)
	return l.SetEnvironment(in)
}

func (s *LizardAgentServer) CreatePolicy(ctx context.Context, in *agent.CreatePolicyRequest) (*agent.Response, error) {
	l := logic.NewCreatePolicyLogic(ctx, s.svcCtx)
	return l.CreatePolicy(in)
}

func (s *LizardAgentServer) Backup(in *agent.BackupRequest, stream agent.LizardAgent_BackupServer) error {
	l := logic.NewBackupLogic(stream.Context(), s.svcCtx)
	return l.Backup(in, stream)
}

func (s *LizardAgentServer) Restore(in *agent.RestoreRequest, stream agent.LizardAgent_RestoreServer) error {
	l := logic.NewRestoreLogic(stream.Context(), s.svcCtx)
	return l.Restore(in, stream)
}
