// Code generated by goctl. DO NOT EDIT.
package types

type Response struct {
	Code    int         `json:"code"`
	Data    interface{} `json:"data,omitempty"`
	Message string      `json:"message,omitempty"`
}

type GetServiceReq struct {
	ServiceName string `path:"service_name"`
}

type CreateRepoReq struct {
	RepoName    string `json:"repo_name"`
	RepoUrl     string `json:"repo_url"`
	S3AccessKey string `json:"s3_access_key"`
	S3SecretKey string `json:"s3_secret_key"`
	Password    string `json:"password"`
}

type StatsRepoReq struct {
	RepoUrl string `form:"repo_url"`
}

type BackupReq struct {
	PolicyId int `form:"policy_id"`
}

type SavePolicyReq struct {
	Id           int      `json:"id,optional"`
	Name         string   `json:"name"`
	RepositoryId int      `json:"repository_id"`
	Hosts        []string `json:"hosts"`
	Cron         string   `json:"cron"`
	BackupDir    string   `json:"backup_dir"`
	Tags         []string `json:"tags,optional"`
	Enable       bool     `json:"enable"`
	Exclude      string   `json:"exclude,optional"`
	Retention    string   `json:"retention"`
}

type ListSnapshotReq struct {
	PolicyId int    `path:"policy_id"`
	Host     string `form:"host"`
	Tag      string `form:"tag,optional"`
	Latest   string `form:"latest,optional"`
}

type SnapshotsIdsReq struct {
	Ids     []string `json:"ids"`
	RepoUrl string   `json:"repo_url"`
}

type FindSnapshotsReq struct {
	RepoUrl    string `form:"repo_url"`
	SnapshotId string `form:"snapshot_id,optional"`
	Host       string `form:"host"`
	Tag        string `form:"tag,optional"`
	Path       string `form:"path,optional"`
	Pattern    string `form:"pattern"`
}

type LsSnapshotsReq struct {
	RepoUrl    string `form:"repo_url"`
	SnapshotId string `form:"snapshot_id"`
	Host       string `form:"host"`
	Dir        string `form:"dir"`
	Tag        string `form:"tag,optional"`
}

type ListHistoryReq struct {
	PolicyName string `form:"policy_name,optional"`
	Page       int    `form:"page,default=1"`
	Size       int    `form:"size,default=20"`
	Search     string `form:"search,optional"`
	Filter     string `form:"filter,optional"`
	Range      string `form:"range,optional"`
	Sort       string `form:"sort,optional"`
}

type RestoreReq struct {
	PolicyId   int    `json:"policy_id"`
	SnapshotId string `json:"snapshot_id"`
	Host       string `json:"host"`
	Exclude    string `json:"exclude,optional"`
	Target     string `json:"target"`
}

type GetDataReq struct {
	Tablename string `path:"tablename"`
	Page      int    `form:"page,default=1"`
	Size      int    `form:"size,default=20"`
	Search    string `form:"search,optional"`
	Filter    string `form:"filter,optional"`
	Range     string `form:"range,optional"`
	Sort      string `form:"sort,optional"`
	Preload   bool   `form:"preload,optional"`
}

type DataByIdReq struct {
	Tablename string `path:"tablename"`
	Id        string `path:"id"`
}

type CreateDataReq struct {
	Tablename string                 `path:"tablename"`
	Body      map[string]interface{} `json:"body"`
}

type UpdateDataReq struct {
	DataByIdReq
	Body map[string]interface{} `json:"body"`
}
